---
- hosts: all
  vars_files:
    - env_variables

  tasks:
    - name: Creating a repository file for Kubernetes
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch

    - name: Adding repository details in Kubernetes repo file
      blockinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        block: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

    - name: Installing Docker and firewalld
      shell: |
        yum install firewalld -y
        yum install -y yum-utils device-mapper-persistent-data lvm2
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum install docker-ce -y

    - name: Disable Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Installing required packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Starting and Enabling the required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

    - name: Enabling Bridge Firewall Rule
      shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
